### ISSUE TITLE
遠端連不上

### ISSUE THREAD

**Issue by sao-coding** [wy414012/rustdesk-server#5]
**Describe the bug**
遠端連不上

**Describe the environment**
 - Install environment: docker
 - If available, the `docker-compose.yaml` file
 ```yml
version: '3.8'

services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: wy368/openrustdesk-server:1
    environment:
      - "RELAY=sao-x.com"
      - "ENCRYPTED_ONLY=1"
    volumes:
      - ./data:/data
    restart: unless-stopped
# 因為使用 docker host mode
# 以防你忘記這些端口:
# 21115 TCP NAT 類型測試
# 21116 TCP TCP 打洞
# 21116 UDP 心跳/ID 伺服器
# 21117 TCP Relay/中繼

```

 - synology dsm7
 - Or if you're running the plain binary, how you're running it
 - In any case, you have to specify the version in use

**How to Reproduce the bug**
1. Given the previously described environment
2. 用 vless + ws + tls + v2rayN

![Image](https://github.com/user-attachments/assets/04365cba-6e18-4289-affc-c4d49c9be98d)

---

### 公共伺服器可以連的上線
![Image](https://github.com/user-attachments/assets/363655ed-c02c-47d2-b916-5106d3156c66)

![Image](https://github.com/user-attachments/assets/38187e69-2083-4ddb-8b88-8ca0c34815f4)

**Expected behavior**
This should happen instead.

**Additional context**

**Notes**
 - Please write in english only. If you provide some images in different languages, you're required to write a translation in english.
 - In any case, **NEVER** put here the content if your `id_ed25519` file
